### ISSUE TITLE
Rubrique Calendrier des activités > nom de domaine à créer : souhaité pour le 26/02

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/squelette-spip-picnat#15]
Créer un nom de domaine propre au raccourci actuel pour aller vers tt les activités de l'asso : suite réunion du 29/01 : on a besoin pour le nouveau calendrier mars/sept : maquette finale le 26/02/16

**Comment by ndamiens** [comment]
j'ai créé http://picnat.fr/cal 
et http://www.picnat.fr/cal
