### ISSUE TITLE
Consultation des activités : cartographie des activités en lien avec l'appli

### ISSUE THREAD

**Issue by SophiePicNat** [picardie-nature/squelette-spip-picnat#18]
avoir une carto des activités sur le site internet (suite réunion du 29/01)

**Comment by ndamiens** [comment]
fait dans @558642d1593b4ad90a2ae59fef0666bcc2b28b37

**Comment by ndamiens** [comment]
fait ici https://github.com/picardie-nature/clicnat-sorties-v1/commit/558642d1593b4ad90a2ae59fef0666bcc2b28b37
