### ISSUE TITLE
Couleur des pôles

### ISSUE THREAD

**Issue by drousseau** [picardie-nature/squelette-spip-picnat#5]
Il faudrait mettre à jour la CSS et les images pour reprendre les nouvelles couleurs des pôles (utilisées dans la version papier du calendrier des sorties).

Il faudra également adapter la dénomiation des pôles.

**Comment by ndamiens** [comment]
J'ai démarré une branch "less" avec la mise à jour des images et l'utilisation de less.js pour la CSS

**Comment by drousseau** [comment]
Bonne idée d'utiliser du meta-css, mais je préfèrerais pour "en ligne" une version sans js, par exemple précompilée, ou en passant dans lessphp

**Comment by ndamiens** [comment]
J'ai fait old school avec un Makefile et lessc

**Comment by ndamiens** [comment]
Pour le picto avocette utiliser la couleur #014249
